name: Test Cygwin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    name: Cygwin Python 3.8

    steps:
      - name: Checkout Pillow
        uses: actions/checkout@v2
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: >
            libfreetype-devel libimagequant-devel libjpeg-devel
            liblcms2-devel libopenjp2-devel libraqm-devel
            libtiff-devel libwebp-devel libxcb-devel netpbm
            ImageMagick jpeg xorg-server-extra xorg-server-common
            xinit python38-setuptools python38-devel python38-tkinter
            python38-wheel python38-pip python38-olefile
            python38-numpy python38-pytest python38-sphinx
            python38-packaging python38-cffi
            libfribidi-devel zlib-devel libX11-xcb-devel tcl-tk-devel
          install-dir: 'C:\tools\cygwin'
      - name: Clean up path
        uses: egor-tensin/cleanup-path@v2
        with:
          dirs: 'C:\tools\cygwin\bin;C:\tools\cygwin\lib\lapack'
      - name: Ensure python dependencies installed
        run: |
          C:\tools\cygwin\bin\python3.8 -m pip install pip wheel setuptools
          C:\tools\cygwin\bin\python3.8 -m pip install -r requirements.txt
      - name: Build Pillow
        run: |
          C:\tools\cygwin\bin\python3.8 setup.py bdist_wheel
      - name: Install Pillow
        run: |
          C:\tools\cygwin\bin\dash -c '/usr/bin/python3.8 -m pip install dist/*.whl'
      - name: Test Pillow
        run: |
          C:\tools\cygwin\bin\python3.8 selftest.py
          C:\tools\cygwin\bin\xvfb-run -s '-screen 0 1024x768x24' .ci/test.sh
