name: Test Cygwin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    name: Cygwin Python 3.8

    steps:
      - name: Checkout Pillow
        uses: actions/checkout@v2
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: >
            python38-devel python38-tkinter libfreetype-devel
            libimagequant-devel libjpeg-devel liblcms2-devel
            libopenjp2-devel libraqm-devel libtiff-devel libwebp-devel
            libxcb-devel python38-olefile python38-pathlib
            python38-numpy netpbm ImageMagick jpeg xorg-server-extra
            xorg-server-common xinit python38-setuptools
            python38-wheel
          install-dir: 'C:\tools\cygwin'
      - name: Clean up path
        uses: egor-tensin/cleanup-path@v2
        with:
          dirs: 'C:\tools\cygwin\bin;C:\tools\cygwin\lib\lapack'
      - name: Build Pillow
        shell: 'C:\tools\cygwin\bin\dash.exe {0}'
        run: |
          /usr/bin/python3.8 setup.py bdist_wheel
      - name: Install Pillow
        shell: 'C:\tools\cygwin\bin\dash.exe {0}'
        run: |
          /usr/bin/python3.8 -m pip install Pillow-*-cp38-cp38-cygwin_*_x86_64.whl
      - name: Test Pillow
        shell: 'C:\tools\cygwin\bin\dash.exe {0}'
        run: |
          /usr/bin/python3.8 selftest.py
          xvfb-run -s '-screen 0 1024x768x24' .ci/test.sh
